#!/usr/bin/env python3

from PyQt4 import QtGui
from PyQt4.QtCore import QUrl
import signal
from subprocess import call
import sys

import mainwindow

class KitchenControl(QtGui.QMainWindow, mainwindow.Ui_MainWindow):
    def __init__(self):
        super(self.__class__, self).__init__()
        self.setupUi(self)

        self.reboot.clicked.connect(lambda: call(['sudo', 'reboot']))
        self.shutdown.clicked.connect(lambda: call(['sudo', 'shutdown', '-h', 'now']))
        self.reload.clicked.connect(lambda: self.load())

        self.load()

    def load(self):
        self.left.load(QUrl('http://homer.binary.kitchen'))
        self.right.load(QUrl('http://matrix.binary.kitchen'))


def main():
    app = QtGui.QApplication(sys.argv)
    form = KitchenControl()
    form.showFullScreen()
    app.exec_()


if __name__ == '__main__':
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    main()
